### PR TITLE
Add Installation Instructions

### LINKED ISSUE #4: Update README.md
For getting started it would be nice to have an up to date README.md which tells you which Environments have to be set and how to get the project up and running for local development.

### PR DESCRIPTION
**Pull request by felixSchober**
add installation instructions

Fixes #4

### CODE REVIEW

**Comment by felixSchober** [comment]
Bitte einmal Prozess, der in der Readme beschrieben ist durchspielen @urmade

**Review by urmade — CHANGES_REQUESTED** [review]
The app is not installed in the test tenant, therefore authentication after running the app fails.

Sorry, but we’re having trouble signing you in.

AADSTS500011: The resource principal named https://4e8978e9-8303-4e00-b180-0e96fc1fe7dc/Api was not found in the tenant named 323593ac-22c0-49aa-9467-4b4d1a786516. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

**Comment by felixSchober** [comment]
ok... strange 
the resource principal should be api://4e8978e9-8303-4e00-b180-0e96fc1fe7dc/Api instead of https://4e8978e9-8303-4e00-b180-0e96fc1fe7dc/Api

Can you make sure that it looks like this when you click on authorize?
image

**Comment by urmade** [comment]
image


Scope has https: attachment in the code by default (only thing I changed was inserting the appsettings.Development.json as proposed in the README / mail).


image

**Comment by felixSchober** [comment]
ahh seems like you are at master. Can you change to the dev branch and try again?

**Comment by urmade** [comment]
Tested on Dev branch, scope is now displayed correctly (api://...). Login error now that the redirect URL is not configured for app. 
Redirect URI from request: http://localhost:5000/swagger/oauth2-redirect.html

image

**Comment by felixSchober** [comment]
Great :)
this is just a Visual Studio on Mac issue (VS on Mac doesn't read some project settings). Should be fixed now.

**Review by urmade — APPROVED** [review]

**Pull request merged**
